spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/support_db  # Replace with your DB name
      username: postgres       # Default PostgreSQL username
      password: postgres       # Default PostgreSQL password
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: create    # Auto-create/update tables
      show-sql: true        # Optional: Show SQL in logs
    application:
        name: notification
    mail:
      host: smtp.gmail.com # Example for Gmail
      port: 587
      username: shaoogrin@gmail.com
      password: qewz vamf upfw kjjv # Use an app password for Gmail
      properties:
        mail:
          smtp:
            auth: true
            starttls.enable: true
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "com.example.ticket.event"

twilio:
  account-sid: AC88437d4c6fc9d6e937ed5e921ea58a41
  auth-token: 3f286432edf93ac5a3262247e75dfe7b
  phone-number: +17579948300 # Your Twilio phone number

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083